<?php

use App\Domain\Admin\TotpService;
use App\Filament\Pages\Auth\Login;
use App\Filament\Pages\TwoFactor;
use App\Models\AuditLog;
use App\Models\User;
use Livewire\Livewire;
use PragmaRX\Google2FA\Google2FA;

/**
 * TASK-ADM-011 / NFR-SEC-012 — admin 2FA (TOTP).
 */
beforeEach(function () {
    $this->admin = User::factory()->systemAdmin()->create(['username' => 'sysadmin']);
});

function totpCode(string $secret, int $offset = 0): string
{
    return str_pad((string) (new Google2FA)->getCurrentOtp($secret), 6, '0', STR_PAD_LEFT);
}

test('ADM-011 login without 2FA enrolled needs only username + password', function () {
    Livewire::test(Login::class)
        ->fillForm(['login' => 'sysadmin', 'password' => 'Password123!'])
        ->call('authenticate')
        ->assertHasNoErrors();
});

test('ADM-011 enrolled admin needs a valid TOTP code', function () {
    $totp = app(TotpService::class);
    $secret = $totp->generateSecret();
    $totp->enroll($this->admin, $secret, totpCode($secret));

    Livewire::test(Login::class)
        ->fillForm(['login' => 'sysadmin', 'password' => 'Password123!', 'totp' => '000000'])
        ->call('authenticate')
        ->assertHasErrors(['data.totp']);

    $this->get('/admin/users')->assertRedirect('/admin/login');

    // correct code passes
    Livewire::test(Login::class)
        ->fillForm(['login' => 'sysadmin', 'password' => 'Password123!', 'totp' => totpCode($secret)])
        ->call('authenticate')
        ->assertHasNoErrors();
});

test('ADM-011 a wrong password never reaches the TOTP check (no enrollment oracle)', function () {
    $totp = app(TotpService::class);
    $secret = $totp->generateSecret();
    $totp->enroll($this->admin, $secret, totpCode($secret));

    Livewire::test(Login::class)
        ->fillForm(['login' => 'sysadmin', 'password' => 'wrong-password', 'totp' => totpCode($secret)])
        ->call('authenticate')
        ->assertHasErrors() // credential failure, not a totp-field error
        ->assertHasNoErrors(['data.totp']);
});

test('ADM-011 enroll via the TwoFactor page: bad code rejected, good code enables + audits', function () {
    Livewire::actingAs($this->admin, 'admin')
        ->test(TwoFactor::class)
        ->call('generateSecret')
        ->call('confirm')
        ->assertNotified(); // no code filled → rejected, asks to retry

    expect($this->admin->refresh()->totp_enabled_at)->toBeNull();

    // fill a live code for the pending secret (regenerated by the call above)
    $page = Livewire::actingAs($this->admin, 'admin')->test(TwoFactor::class);
    $page->call('generateSecret');
    $secret = $page->get('pendingSecret');

    $page
        ->fillForm(['code' => totpCode($secret)])
        ->call('confirm');

    expect($this->admin->refresh()->totp_enabled_at)->not->toBeNull()
        ->and(AuditLog::query()->where('action', 'admin.2fa_enabled')->where('target_id', $this->admin->id)->exists())->toBeTrue();

    // disable audited too
    $page->call('disable');
    expect($this->admin->refresh()->totp_enabled_at)->toBeNull()
        ->and(AuditLog::query()->where('action', 'admin.2fa_disabled')->exists())->toBeTrue();
});

test('ADM-011 secret is encrypted at rest and never serialized', function () {
    $totp = app(TotpService::class);
    $secret = $totp->generateSecret();
    $totp->enroll($this->admin, $secret, totpCode($secret));

    $raw = DB::table('users')->where('id', $this->admin->id)->value('totp_secret');

    expect($raw)->not->toBe($secret)
        ->and($raw)->toStartWith('eyJ') // Laravel encrypted:{"iv","value","mac"} JSON, base64
        ->and($this->admin->makeHidden('password_hash')->toArray())->not->toHaveKey('totp_secret');
});
