/** FR-ROOM-004 / DEC-096 — add-members dialog strings (local, like rename-text). */
export const addMembersText = {
  th: {
    menu: 'เพิ่มสมาชิก',
    title: 'เพิ่มสมาชิกเข้ากลุ่ม',
    subtitle: 'เลือกคนใน workspace ที่ยังไม่ได้อยู่ในกลุ่มนี้',
    label: 'ค้นหาสมาชิก',
    placeholder: 'พิมพ์ชื่อหรือ username',
    close: 'ปิด',
    cancel: 'ยกเลิก',
    add: 'เพิ่ม {n} คน',
    addNone: 'เพิ่ม',
    adding: 'กำลังเพิ่ม…',
    selected: 'เลือกแล้ว {n} คน',
    clear: 'ล้างที่เลือก',
    inGroup: 'อยู่ในกลุ่มแล้ว',
    loading: 'กำลังโหลด…',
    loadMore: 'โหลดเพิ่ม',
    empty: 'ไม่พบสมาชิกที่ตรงกับ “{q}”',
    emptyAll: 'ไม่มีสมาชิกใน workspace',
    limit: 'เลือกได้สูงสุด 100 คนต่อครั้ง',
    done: 'เพิ่มสมาชิกเข้ากลุ่มแล้ว {n} คน',
    errLoad: 'โหลดรายชื่อไม่สำเร็จ',
    retry: 'ลองอีกครั้ง',
    errForbidden: 'คุณไม่มีสิทธิ์เพิ่มสมาชิกในกลุ่มนี้แล้ว',
    errFull: 'กลุ่มเต็มแล้ว ไม่สามารถเพิ่มสมาชิกได้',
    errNetwork: 'เชื่อมต่อไม่ได้ ตรวจสอบอินเทอร์เน็ตแล้วลองอีกครั้ง',
    errGeneric: 'เพิ่มสมาชิกไม่สำเร็จ กรุณาลองอีกครั้ง',
  },
  en: {
    menu: 'Add members',
    title: 'Add members to the group',
    subtitle: 'Pick people in this workspace who are not in the group yet.',
    label: 'Search members',
    placeholder: 'Type a name or username',
    close: 'Close',
    cancel: 'Cancel',
    add: 'Add {n}',
    addNone: 'Add',
    adding: 'Adding…',
    selected: '{n} selected',
    clear: 'Clear selection',
    inGroup: 'In group',
    loading: 'Loading…',
    loadMore: 'Load more',
    empty: 'No members match “{q}”',
    emptyAll: 'No members in this workspace',
    limit: 'You can pick up to 100 people at a time',
    done: 'Added {n} to the group',
    errLoad: 'Could not load the member list',
    retry: 'Try again',
    errForbidden: 'You no longer have permission to add members to this group.',
    errFull: 'The group is full, so no more members can be added.',
    errNetwork: 'Could not connect. Check your internet and try again.',
    errGeneric: 'Could not add members. Please try again.',
  },
};
export type AddMembersTextKey = keyof typeof addMembersText.th;
