/** FR-PROF-006 — profile photo editor strings (local, like privacy-text). */
export const avatarText = {
  th: {
    menu: 'เปลี่ยนรูปโปรไฟล์',
    title: 'รูปโปรไฟล์',
    subtitle: 'ทุกคนในเวิร์กสเปซจะเห็นรูปนี้ข้างชื่อของคุณ',
    close: 'ปิด',
    dropTitle: 'ลากรูปมาวางที่นี่',
    dropOr: 'หรือ',
    choose: 'เลือกรูป',
    chooseOther: 'เลือกรูปอื่น',
    pasteHint: 'วางรูปจากคลิปบอร์ดได้ด้วย (Ctrl+V)',
    formats: 'JPG, PNG, WebP หรือ GIF · ไม่เกิน 5 MB',
    stage: 'ตำแหน่งรูป ลากเพื่อเลื่อน ใช้ปุ่มลูกศรเพื่อขยับ และ + / − เพื่อซูม',
    zoom: 'ซูม',
    zoomOut: 'ซูมออก',
    zoomIn: 'ซูมเข้า',
    dragHint: 'ลากเพื่อจัดตำแหน่ง',
    gifBadge: 'GIF เคลื่อนไหว',
    gifHint: 'GIF จะถูกครอปตรงกลางอัตโนมัติ เพื่อให้ภาพเคลื่อนไหวคงอยู่',
    current: 'รูปปัจจุบัน',
    noPhoto: 'ยังไม่มีรูป ตอนนี้ทุกคนเห็นตัวอักษรย่อของคุณ',
    save: 'บันทึก',
    saving: 'กำลังบันทึก…',
    cancel: 'ยกเลิก',
    remove: 'ลบรูป',
    removeTitle: 'ลบรูปโปรไฟล์?',
    removeBody: 'ทุกคนจะเห็นตัวอักษรย่อของชื่อคุณแทน',
    keep: 'เก็บไว้',
    confirmRemove: 'ลบรูป',
    removing: 'กำลังลบ…',
    preparing: 'กำลังเตรียมรูป…',
    uploading: 'กำลังอัปโหลด {p}%',
    processing: 'กำลังประมวลผลรูป…',
    applying: 'กำลังตั้งเป็นรูปโปรไฟล์…',
    errType: 'ใช้ได้เฉพาะไฟล์ JPG, PNG, WebP หรือ GIF',
    errSize: 'รูปนี้ใหญ่เกิน 5 MB ลองย่อรูปหรือเลือกรูปอื่น',
    errEmpty: 'ไฟล์นี้ว่างเปล่า ลองเลือกรูปอื่น',
    errDecode: 'เปิดรูปนี้ไม่ได้ ไฟล์อาจเสียหาย ลองเลือกรูปอื่น',
    errInvalid: 'ตั้งรูปนี้ไม่ได้ กรุณาอัปโหลดใหม่อีกครั้ง',
    errServerSize: 'เซิร์ฟเวอร์ปฏิเสธเพราะไฟล์ใหญ่เกินกำหนด ลองรูปที่เล็กลง',
    errProcessing: 'ประมวลผลรูปไม่สำเร็จ ลองอีกครั้งหรือเลือกรูปอื่น',
    errNetwork: 'เชื่อมต่อไม่ได้ ตรวจสอบอินเทอร์เน็ตแล้วลองอีกครั้ง',
    errRemove: 'ลบรูปไม่สำเร็จ กรุณาลองอีกครั้ง',
    saved: 'บันทึกรูปโปรไฟล์แล้ว',
  },
  en: {
    menu: 'Change profile photo',
    title: 'Profile photo',
    subtitle: 'Everyone in your workspace sees this next to your name.',
    close: 'Close',
    dropTitle: 'Drop a photo here',
    dropOr: 'or',
    choose: 'Choose photo',
    chooseOther: 'Choose another',
    pasteHint: 'You can also paste an image (Ctrl+V)',
    formats: 'JPG, PNG, WebP or GIF · up to 5 MB',
    stage: 'Photo position. Drag to move, arrow keys to nudge, + and − to zoom',
    zoom: 'Zoom',
    zoomOut: 'Zoom out',
    zoomIn: 'Zoom in',
    dragHint: 'Drag to reposition',
    gifBadge: 'Animated GIF',
    gifHint: 'GIFs are centre-cropped automatically so the animation is kept.',
    current: 'Current photo',
    noPhoto: 'No photo yet. People see your initials for now.',
    save: 'Save',
    saving: 'Saving…',
    cancel: 'Cancel',
    remove: 'Remove photo',
    removeTitle: 'Remove your profile photo?',
    removeBody: 'People will see your initials instead.',
    keep: 'Keep it',
    confirmRemove: 'Remove',
    removing: 'Removing…',
    preparing: 'Preparing photo…',
    uploading: 'Uploading {p}%',
    processing: 'Processing photo…',
    applying: 'Setting your photo…',
    errType: 'Only JPG, PNG, WebP or GIF images can be used.',
    errSize: 'This photo is larger than 5 MB. Try a smaller one.',
    errEmpty: 'This file is empty. Try another photo.',
    errDecode: 'This image could not be opened. It may be damaged.',
    errInvalid: 'That photo could not be set. Please upload it again.',
    errServerSize: 'The server refused this file as too large. Try a smaller photo.',
    errProcessing: 'The photo could not be processed. Try again or pick another.',
    errNetwork: 'Could not connect. Check your connection and try again.',
    errRemove: 'Could not remove your photo. Please try again.',
    saved: 'Profile photo saved',
  },
} as const;
export type AvatarTextKey = keyof typeof avatarText.th;
