/** FR-PROF-006 / FR-PROF-008 — profile + group photo editor strings (local, like privacy-text). */
export const avatarText = {
  th: {
    menu: 'เปลี่ยนรูปโปรไฟล์',
    title: 'รูปโปรไฟล์',
    subtitle: 'ทุกคนในเวิร์กสเปซจะเห็นรูปนี้ข้างชื่อของคุณ',
    close: 'ปิด',
    dropTitle: 'ลากรูปมาวางที่นี่',
    dropOr: 'หรือ',
    choose: 'เลือกรูป',
    chooseOther: 'เลือกรูปอื่น',
    pasteHint: 'วางรูปจากคลิปบอร์ดได้ด้วย (Ctrl+V)',
    formats: 'JPG, PNG, WebP หรือ GIF · ไม่เกิน 5 MB',
    stage: 'ตำแหน่งรูป ลากเพื่อเลื่อน ใช้ปุ่มลูกศรเพื่อขยับ และ + / − เพื่อซูม',
    zoom: 'ซูม',
    zoomOut: 'ซูมออก',
    zoomIn: 'ซูมเข้า',
    dragHint: 'ลากเพื่อจัดตำแหน่ง',
    gifBadge: 'GIF เคลื่อนไหว',
    gifHint: 'GIF จะถูกครอปตรงกลางอัตโนมัติ เพื่อให้ภาพเคลื่อนไหวคงอยู่',
    current: 'รูปปัจจุบัน',
    noPhoto: 'ยังไม่มีรูป ตอนนี้ทุกคนเห็นตัวอักษรย่อของคุณ',
    save: 'บันทึก',
    saving: 'กำลังบันทึก…',
    cancel: 'ยกเลิก',
    remove: 'ลบรูป',
    removeTitle: 'ลบรูปโปรไฟล์?',
    removeBody: 'ทุกคนจะเห็นตัวอักษรย่อของชื่อคุณแทน',
    keep: 'เก็บไว้',
    confirmRemove: 'ลบรูป',
    removing: 'กำลังลบ…',
    preparing: 'กำลังเตรียมรูป…',
    uploading: 'กำลังอัปโหลด {p}%',
    processing: 'กำลังประมวลผลรูป…',
    applying: 'กำลังตั้งเป็นรูปโปรไฟล์…',
    errType: 'ใช้ได้เฉพาะไฟล์ JPG, PNG, WebP หรือ GIF',
    errSize: 'รูปนี้ใหญ่เกิน 5 MB ลองย่อรูปหรือเลือกรูปอื่น',
    errEmpty: 'ไฟล์นี้ว่างเปล่า ลองเลือกรูปอื่น',
    errDecode: 'เปิดรูปนี้ไม่ได้ ไฟล์อาจเสียหาย ลองเลือกรูปอื่น',
    errInvalid: 'ตั้งรูปนี้ไม่ได้ กรุณาอัปโหลดใหม่อีกครั้ง',
    errServerSize: 'เซิร์ฟเวอร์ปฏิเสธเพราะไฟล์ใหญ่เกินกำหนด ลองรูปที่เล็กลง',
    errProcessing: 'ประมวลผลรูปไม่สำเร็จ ลองอีกครั้งหรือเลือกรูปอื่น',
    errNetwork: 'เชื่อมต่อไม่ได้ ตรวจสอบอินเทอร์เน็ตแล้วลองอีกครั้ง',
    errRemove: 'ลบรูปไม่สำเร็จ กรุณาลองอีกครั้ง',
    errForbidden: 'คุณไม่มีสิทธิ์เปลี่ยนรูปนี้แล้ว',
    saved: 'บันทึกรูปโปรไฟล์แล้ว',
  },
  en: {
    menu: 'Change profile photo',
    title: 'Profile photo',
    subtitle: 'Everyone in your workspace sees this next to your name.',
    close: 'Close',
    dropTitle: 'Drop a photo here',
    dropOr: 'or',
    choose: 'Choose photo',
    chooseOther: 'Choose another',
    pasteHint: 'You can also paste an image (Ctrl+V)',
    formats: 'JPG, PNG, WebP or GIF · up to 5 MB',
    stage: 'Photo position. Drag to move, arrow keys to nudge, + and − to zoom',
    zoom: 'Zoom',
    zoomOut: 'Zoom out',
    zoomIn: 'Zoom in',
    dragHint: 'Drag to reposition',
    gifBadge: 'Animated GIF',
    gifHint: 'GIFs are centre-cropped automatically so the animation is kept.',
    current: 'Current photo',
    noPhoto: 'No photo yet. People see your initials for now.',
    save: 'Save',
    saving: 'Saving…',
    cancel: 'Cancel',
    remove: 'Remove photo',
    removeTitle: 'Remove your profile photo?',
    removeBody: 'People will see your initials instead.',
    keep: 'Keep it',
    confirmRemove: 'Remove',
    removing: 'Removing…',
    preparing: 'Preparing photo…',
    uploading: 'Uploading {p}%',
    processing: 'Processing photo…',
    applying: 'Setting your photo…',
    errType: 'Only JPG, PNG, WebP or GIF images can be used.',
    errSize: 'This photo is larger than 5 MB. Try a smaller one.',
    errEmpty: 'This file is empty. Try another photo.',
    errDecode: 'This image could not be opened. It may be damaged.',
    errInvalid: 'That photo could not be set. Please upload it again.',
    errServerSize: 'The server refused this file as too large. Try a smaller photo.',
    errProcessing: 'The photo could not be processed. Try again or pick another.',
    errNetwork: 'Could not connect. Check your connection and try again.',
    errRemove: 'Could not remove your photo. Please try again.',
    errForbidden: 'You no longer have permission to change this photo.',
    saved: 'Profile photo saved',
  },
} as const;
export type AvatarTextKey = keyof typeof avatarText.th;

/**
 * FR-PROF-008 / DEC-090 — the same editor, pointed at a group. Only what
 * differs is overridden; everything else (crop, GIF, upload and error copy)
 * is shared with the profile photo.
 */
export const roomAvatarText: Record<'th' | 'en', Partial<Record<AvatarTextKey, string>>> = {
  th: {
    menu: 'เปลี่ยนรูปกลุ่ม',
    title: 'เปลี่ยนรูปกลุ่ม',
    subtitle: 'สมาชิกทุกคนในกลุ่มจะเห็นรูปนี้ในรายการแชทและหัวข้อห้อง',
    current: 'รูปกลุ่มปัจจุบัน',
    noPhoto: 'กลุ่มนี้ยังไม่มีรูป ตอนนี้ทุกคนเห็นตัวอักษรย่อของชื่อกลุ่ม',
    pasteHint: 'วางรูปจากคลิปบอร์ดได้ด้วย (Ctrl+V)',
    removeTitle: 'ลบรูปกลุ่ม?',
    removeBody: 'ทุกคนจะเห็นตัวอักษรย่อของชื่อกลุ่มแทน',
    applying: 'กำลังตั้งเป็นรูปกลุ่ม…',
    errRemove: 'ลบรูปกลุ่มไม่สำเร็จ กรุณาลองอีกครั้ง',
  },
  en: {
    menu: 'Change group photo',
    title: 'Change group photo',
    subtitle: 'Everyone in this group sees it in the chat list and the room header.',
    current: 'Current group photo',
    noPhoto: 'No group photo yet. People see the group initials for now.',
    removeTitle: 'Remove the group photo?',
    removeBody: 'People will see the group initials instead.',
    applying: 'Setting the group photo…',
    errRemove: 'Could not remove the group photo. Please try again.',
  },
};

/** FR-WS-004 / DEC-093 — same editor, workspace wording. */
export const workspaceAvatarText: Record<'th' | 'en', Partial<Record<AvatarTextKey, string>>> = {
  th: {
    menu: 'เปลี่ยนรูป workspace',
    title: 'เปลี่ยนรูป workspace',
    subtitle: 'ทุกคนใน workspace จะเห็นรูปนี้ที่แถบด้านข้าง',
    current: 'รูป workspace ปัจจุบัน',
    noPhoto: 'workspace นี้ยังไม่มีรูป ตอนนี้ทุกคนเห็นตัวอักษรย่อของชื่อ',
    pasteHint: 'วางรูปจากคลิปบอร์ดได้ด้วย (Ctrl+V)',
    removeTitle: 'ลบรูป workspace?',
    removeBody: 'ทุกคนจะเห็นตัวอักษรย่อของชื่อ workspace แทน',
    applying: 'กำลังตั้งเป็นรูป workspace…',
    errRemove: 'ลบรูป workspace ไม่สำเร็จ กรุณาลองอีกครั้ง',
  },
  en: {
    menu: 'Change workspace photo',
    title: 'Change workspace photo',
    subtitle: 'Everyone in the workspace sees it in the sidebar.',
    current: 'Current workspace photo',
    noPhoto: 'No workspace photo yet. People see the name initial for now.',
    removeTitle: 'Remove the workspace photo?',
    removeBody: 'People will see the workspace initial instead.',
    applying: 'Setting the workspace photo…',
    errRemove: 'Could not remove the workspace photo. Please try again.',
  },
};
